### ISSUE TITLE
[BUG] Deployment

### ISSUE THREAD

**Issue by orangejuiceplz** [NoGambling1/ConsoleGames#12]
**Describe the bug**

a deployment issue

**To Reproduce**

commit anything

**Expected behavior**

deploys to pypi

**Screenshots**
no sc

**Desktop (please complete the following information):**
(if you are on **LINUX** please add your distro as well)
 - OS: Linux - Arch Stable
 - browser Firefox
 - version dfk

**Fix**

Update REPO secrets @NoGambling1

**Comment by NoGambling1** [comment]
Grr

**Comment by orangejuiceplz** [comment]
Fixed

Closing #12
