### ISSUE TITLE
Snake not working on windows

### ISSUE THREAD

**Issue by NoGambling1** [NoGambling1/ConsoleGames#3]
TermIOS is a linux/macOS only extension. We can make 2 verisons of the entire project, Windows and linux/MacOS in the future

**Comment by orangejuiceplz** [comment]
I can probably find the correct library for both, I'll work on that when I can. No need to work on two entire separate versions as of now as the project is small so our libraries are small.  In the future, maybe. If thats the case then we could probably split it up like this: 

You can handle the windows version of the project, and I will handle the Unix stuff.

I'll begin working on this now.  -- I have created a new branch for this issue and will make a PR with my changes. I don't exactly have access to my windows PC at the moment, so you're going to have to do that for me.

I could try to see if I can SSH in, but I'm not sure.

**Comment by NoGambling1** [comment]
Okay my pookie wookie

**Comment by orangejuiceplz** [comment]
Please review the PR as it contains the change for Microsoft Windows.

Merge if it it works.
